id: PF04F544F
initial_creation_type: ocr
source_metadata:
  volumes:
    964b374f7ff94e05a79cb93ea025e1cd:
      base_file: v072.txt
      image_group_id: I1PD95917
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་དངོས་གཞིའི་ས་མང་པོ།
      total_pages: 1406
      volume_number: 72
